/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */

/* eslint-disable */

import { createComponent } from '@stencil/react-output-target/runtime';
import { UiButton as UiButtonElement, defineCustomElement as defineUiButton } from "@support-library/ui/components/ui-button.js";
import React from 'react';

type UiButtonEvents = NonNullable<unknown>;

export const UiButton = /*@__PURE__*/ createComponent<UiButtonElement, UiButtonEvents>({
    tagName: 'ui-button',
    elementClass: UiButtonElement,
    react: React,
    events: {} as UiButtonEvents,
    defineCustomElement: defineUiButton
});
