name: Deploy to Azure Storage (Storybook e Projeto)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      # Gera os arquivos estáticos do Storybook (pasta storybook-static)
      - name: Build Storybook
        run: npm run build-sb

      # Gera a build do projeto (pasta dist)
      - name: Build Projeto
        run: npm run build

      # Faz login no Azure usando o Service Principal
      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Upload dos arquivos do Storybook para o container "storybook"
      - name: Upload Storybook to Blob
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name cdnexamples \
              --destination storybook \
              --source storybook-static \
              --pattern "*" \
              --overwrite true
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}

      # Upload dos arquivos do projeto para o container "cdn"
      - name: Upload Project Dist to Blob (CDN)
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name cdnexamples \
              --destination cdn \
              --source dist \
              --pattern "*" \
              --overwrite true
        env:
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
