name: Deploy Storybook to Azure Storage

on:
  push:
    branches:
      - main  # Ou a branch que você quiser

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build Storybook
        run: npm run build-sb  # Gera a pasta storybook-static

      # 1) Faz login no Azure usando o Service Principal
      - name: Login Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 2) Faz o upload dos arquivos para o contêiner "storybook"
      - name: Upload to Blob
        uses: azure/cli@v1
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name cdnexamples \
              --container-name storybook \
              --source storybook-static \
              --pattern "*"
        env:
          # Passa a Storage Key como variável de ambiente para o CLI
          AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
